name: Deploy to Heroku Prod

on:
  push:
    branches:
      - master

jobs:
  deploy-to-production:
    name: Deploy to Heroku Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "migarjo-ruby-books" #Must be unique in Heroku
          heroku_email: "mjohn174@gmail.com"
