# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
        
jobs:
  test:
    name: Run Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true  
    - name: Install dependencies
      run: bundle install
    - name: Run db config
      run: chmod +x Automation/configure-install-db.sh ; ./Automation/configure-install-db.sh
    - name: Run tests
      run: bundle exec rake
  deploy-to-production:
    name: Deploy to Heroku Prod
    if: ${{github.ref == 'ref/head/master'}}
    runs-on: ubuntu-latest
    steps:
      - name: start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "migarjo-ruby-books" #Must be unique in Heroku
          heroku_email: "mjohn174@gmail.com"
      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env_url: "https://migarjo-ruby-books.herokuapp.com/" 
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}     
  deploy-to-review:
    name: Deploy to Heroku Review
    if: ${{github.ref != 'ref/head/master'}}
    runs-on: ubuntu-latest
    steps:
      - name: start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: review
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "migarjo-ruby-books-review"
          heroku_email: "mjohn174@gmail.com"
      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env_url: "https://migarjo-ruby-books-review.herokuapp.com/" 
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}     
